"""empty message

Revision ID: 3eb2f5e72c4b
Revises: ccb55d267550
Create Date: 2020-12-11 12:40:19.288688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb2f5e72c4b'
down_revision = 'ccb55d267550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguidores',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_usuario_seguido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_seguido'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_usuario_seguido')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguidores')
    # ### end Alembic commands ###
