"""empty message

Revision ID: 893d0c68cf52
Revises: 
Create Date: 2020-12-09 17:33:57.444950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893d0c68cf52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuário',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('senha', sa.String(length=15), nullable=False),
    sa.Column('telefone', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('senha'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('Post',
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=200), nullable=True),
    sa.Column('midia', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuário.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_post')
    )
    op.create_table('Seguidor',
    sa.Column('id_seguidor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_usuario_seguido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuário.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_seguido'], ['Usuário.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_seguidor')
    )
    op.create_table('Status',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('midia', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuário.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_table('Comentário',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id_post'], ['Post.id_post'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuário.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('Curtida',
    sa.Column('id_curtida', sa.Integer(), nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['Post.id_post'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuário.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_curtida')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Curtida')
    op.drop_table('Comentário')
    op.drop_table('Status')
    op.drop_table('Seguidor')
    op.drop_table('Post')
    op.drop_table('Usuário')
    # ### end Alembic commands ###
