"""empty message

Revision ID: 8eba51809f4d
Revises: ce4db2250503
Create Date: 2020-12-11 14:01:37.617022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eba51809f4d'
down_revision = 'ce4db2250503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Status',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('midia', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_table('Comentário',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id_post'], ['Post.id_post'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('Curtida',
    sa.Column('id_curtida', sa.Integer(), nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['Post.id_post'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_curtida')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Curtida')
    op.drop_table('Comentário')
    op.drop_table('Status')
    # ### end Alembic commands ###
