"""empty message

Revision ID: ccb55d267550
Revises: 893d0c68cf52
Create Date: 2020-12-11 11:05:53.114356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb55d267550'
down_revision = '893d0c68cf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=False),
    sa.Column('userPhoto', sa.String(length=100), nullable=False),
    sa.Column('photoMessage', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.drop_table('Curtida')
    op.drop_table('Usuário')
    op.drop_table('Status')
    op.drop_table('Post')
    op.drop_table('Comentário')
    op.drop_table('Seguidor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Seguidor',
    sa.Column('id_seguidor', sa.INTEGER(), nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('id_usuario_seguido', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuário.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_seguido'], ['Usuário.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_seguidor')
    )
    op.create_table('Comentário',
    sa.Column('id_comentario', sa.INTEGER(), nullable=False),
    sa.Column('id_post', sa.INTEGER(), nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('texto', sa.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id_post'], ['Post.id_post'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuário.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('Post',
    sa.Column('id_post', sa.INTEGER(), nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('texto', sa.VARCHAR(length=200), nullable=True),
    sa.Column('midia', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuário.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_post')
    )
    op.create_table('Status',
    sa.Column('id_status', sa.INTEGER(), nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('midia', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuário.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_table('Usuário',
    sa.Column('id_usuario', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=15), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=15), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=13), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('senha'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('Curtida',
    sa.Column('id_curtida', sa.INTEGER(), nullable=False),
    sa.Column('id_post', sa.INTEGER(), nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['Post.id_post'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuário.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_curtida')
    )
    op.drop_table('Usuario')
    # ### end Alembic commands ###
