"""empty message

Revision ID: ce4db2250503
Revises: 3eb2f5e72c4b
Create Date: 2020-12-11 13:00:16.693971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4db2250503'
down_revision = '3eb2f5e72c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('midia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_post')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Post')
    # ### end Alembic commands ###
